### ISSUE TITLE
Return the global or local variables into 4D type?

### ISSUE THREAD

**Issue by mesopelagique** [miyako/4d-plugin-python#1]
Hi,

very interesting project!

I am wondering instead of capturing stdout or stderr only, if we could get variables values converted to 4d type in an object _(key=var name, value as 4d type)_

(and in python script we will do a lot of `del xxx` to clean and keep only interesting var at 4D level)

---

instead of `PyRun_SimpleString` 

we could do maybe something like that (inspired from python wrapper for R langage https://github.com/rstudio/reticulate )

```c++
    PyObject* main = PyImport_AddModule("__main__");
    PyObject* globals = PyModule_GetDict(main);
    bool local = true; // allowing to get only new var? 
    if (local) {
        PyObjectPtr locals(PyDict_New());
        PyObjectPtr res(PyRun_StringFlags(python.c_str(), Py_file_input, globals, locals, NULL));
        //  if (res.is_null())todo manage error

        // else todo manage local values
        locals.detach();

    } else {
        PyObjectPtr res(PyRun_StringFlags(python.c_str(), Py_file_input, globals, globals, NULL));
        //  if (res.is_null()) todo manage error

        // else manage global conversion

    }
```

**Comment by miyako** [comment]
I've added a kind of callback today but I need to study your reference more, to understand how to manage variables.

**Comment by miyako** [comment]
I`ve changed the code to map a 4D object to locals()

**Comment by mesopelagique** [comment]
I see the change , good work, I will test for sure
